// Afrique
// const el1 = "./MapSpots/Regions/Afrique/AfriqueSud.json"
const el2 = "./MapSpots/Regions/Afrique/Algerie.json"
// const el3 = "./MapSpots/Regions/Afrique/Angola.json"
// const el4 = "./MapSpots/Regions/Afrique/Benin.json"
const el5 = "./MapSpots/Regions/Afrique/Botswana.json"
// const el6 = "./MapSpots/Regions/Afrique/BurkinaFaso.json"
const el7 = "./MapSpots/Regions/Afrique/Burundi.json"
const el8 = "./MapSpots/Regions/Afrique/Cameroun.json"
const el9 = "./MapSpots/Regions/Afrique/CapVert.json"
// const el10 = "./MapSpots/Regions/Afrique/RepCentrafricaine.json"
// const el11 = "./MapSpots/Regions/Afrique/Comores.json"
// const el12 = "./MapSpots/Regions/Afrique/Congo.json"
const el13 = "./MapSpots/Regions/Afrique/RepDemCongo.json"
// const el14 = "./MapSpots/Regions/Afrique/CoteIvoire.json"
// const el15 = "./MapSpots/Regions/Afrique/Djibouti.json"
const el16 = "./MapSpots/Regions/Afrique/Egypte.json"
// const el17 = "./MapSpots/Regions/Afrique/Erythree.json"
// const el18 = "./MapSpots/Regions/Afrique/Eswatini.json"
const el19 = "./MapSpots/Regions/Afrique/Ethiopie.json"
// const el20 = "./MapSpots/Regions/Afrique/Gabon.json"
// const el21 = "./MapSpots/Regions/Afrique/Gambie.json"
// const el22 = "./MapSpots/Regions/Afrique/Ghana.json"
// const el23 = "./MapSpots/Regions/Afrique/Guinee.json"
// const el24 = "./MapSpots/Regions/Afrique/GuineeBissau.json"
// const el25 = "./MapSpots/Regions/Afrique/GuineeEquat.json"
const el26 = "./MapSpots/Regions/Afrique/Kenya.json"
const el27 = "./MapSpots/Regions/Afrique/Lesotho.json"
// const el28 = "./MapSpots/Regions/Afrique/Liberia.json"
// const el29 = "./MapSpots/Regions/Afrique/Libye.json"
const el30 = "./MapSpots/Regions/Afrique/Madagascar.json"
//const el31 = "./MapSpots/Regions/Afrique/Malawi.json"
const el32 = "./MapSpots/Regions/Afrique/Mali.json"
const el33 = "./MapSpots/Regions/Afrique/Maroc.json"
const el34 = "./MapSpots/Regions/Afrique/Maurice.json"
// const el35 = "./MapSpots/Regions/Afrique/Mauritanie.json"
// const el36 = "./MapSpots/Regions/Afrique/Mozambique.json"
const el37 = "./MapSpots/Regions/Afrique/Namibie.json"
// const el38 = "./MapSpots/Regions/Afrique/Niger.json"
// const el39 = "./MapSpots/Regions/Afrique/Nigeria.json"
// const el40 = "./MapSpots/Regions/Afrique/Ouganda.json"
const el41 = "./MapSpots/Regions/Afrique/Rwanda.json"
// const el42 = "./MapSpots/Regions/Afrique/SaoTomePrincipe.json"
// const el43 = "./MapSpots/Regions/Afrique/Senegal.json"
// const el44 = "./MapSpots/Regions/Afrique/Seychelles.json"
// const el45 = "./MapSpots/Regions/Afrique/SierraLeone.json"
// const el46 = "./MapSpots/Regions/Afrique/Somalie.json"
// const el47 = "./MapSpots/Regions/Afrique/Soudan.json"
// const el48 = "./MapSpots/Regions/Afrique/SudSoudan.json"
const el49 = "./MapSpots/Regions/Afrique/Tanzanie.json"
// const el50 = "./MapSpots/Regions/Afrique/Tchad.json"
// const el51 = "./MapSpots/Regions/Afrique/Togo.json"
// const el52 = "./MapSpots/Regions/Afrique/Tunisie.json"
// const el53 = "./MapSpots/Regions/Afrique/Zambie.json"
// const el54 = "./MapSpots/Regions/Afrique/Zimbabwe.json"

// Amerique
// const el55 = "./MapSpots/Regions/Amerique/AntiguaBarbuda.json"
const el56 = "./MapSpots/Regions/Amerique/Argentine.json"
// const el57 = "./MapSpots/Regions/Amerique/Bahamas.json"
// const el58 = "./MapSpots/Regions/Amerique/Barbade.json"
// const el59 = "./MapSpots/Regions/Amerique/Belize.json"
// const el60 = "./MapSpots/Regions/Amerique/Bolivie.json"
// const el61 = "./MapSpots/Regions/Amerique/Bresil.json"
// const el62 = "./MapSpots/Regions/Amerique/Canada.json"
const el63 = "./MapSpots/Regions/Amerique/Chili.json"
const el64 = "./MapSpots/Regions/Amerique/Colombie.json"
const el65 = "./MapSpots/Regions/Amerique/CostaRica.json"
// const el66 = "./MapSpots/Regions/Amerique/Cuba.json"
// const el67 = "./MapSpots/Regions/Amerique/RepDominicaine.json"
// const el68 = "./MapSpots/Regions/Amerique/Dominique.json"
const el69 = "./MapSpots/Regions/Amerique/Equateur.json"
const el70 = "./MapSpots/Regions/Amerique/EtatsUnis.json"
// const el71 = "./MapSpots/Regions/Amerique/Grenade.json"
const el72 = "./MapSpots/Regions/Amerique/Guatemala.json"
// const el73 = "./MapSpots/Regions/Amerique/Guyana.json"
// const el74 = "./MapSpots/Regions/Amerique/Haiti.json"
// const el75 = "./MapSpots/Regions/Amerique/Honduras.json"
// const el76 = "./MapSpots/Regions/Amerique/Jamaique.json"
const el77 = "./MapSpots/Regions/Amerique/Mexique.json"
const el78 = "./MapSpots/Regions/Amerique/Nicaragua.json"
// const el79 = "./MapSpots/Regions/Amerique/Panama.json"
// const el80 = "./MapSpots/Regions/Amerique/Paraguay.json"
const el81 = "./MapSpots/Regions/Amerique/Perou.json"
// const el82 = "./MapSpots/Regions/Amerique/PortoRico.json"
// const el83 = "./MapSpots/Regions/Amerique/ChristopheNieves.json"
// const el84 = "./MapSpots/Regions/Amerique/SainteLucie.json"
// const el85 = "./MapSpots/Regions/Amerique/VincetGrenadines.json"
// const el86 = "./MapSpots/Regions/Amerique/Salvador.json"
// const el87 = "./MapSpots/Regions/Amerique/Suriname.json"
// const el88 = "./MapSpots/Regions/Amerique/TriniteTobago.json"
// const el89 = "./MapSpots/Regions/Amerique/Uruguay.json"
// const el90 = "./MapSpots/Regions/Amerique/Venezuela.json"

// Asie
// const el91 = "./MapSpots/Regions/Asie/Afghanistan.json"
const el92 = "./MapSpots/Regions/Asie/ArabieSaoudite.json"
// const el93 = "./MapSpots/Regions/Asie/Armenie.json"
// const el94 = "./MapSpots/Regions/Asie/Azerbaidjan.json"
// const el95 = "./MapSpots/Regions/Asie/Bahrein.json"
// const el96 = "./MapSpots/Regions/Asie/Bangladesh.json"
const el97 = "./MapSpots/Regions/Asie/Bhoutan.json"
// const el98 = "./MapSpots/Regions/Asie/Brunei.json"
const el99 = "./MapSpots/Regions/Asie/Cambodge.json"
const el100 = "./MapSpots/Regions/Asie/Chine.json"
// const el101 = "./MapSpots/Regions/Asie/CoreeNord.json"
const el102 = "./MapSpots/Regions/Asie/CoreeSud.json"
// const el103 = "./MapSpots/Regions/Asie/Emirats.json"
const el104 = "./MapSpots/Regions/Asie/Inde.json"
const el105 = "./MapSpots/Regions/Asie/Indonesie.json"
// const el106 = "./MapSpots/Regions/Asie/Irak.json"
const el107 = "./MapSpots/Regions/Asie/Iran.json"
// const el108 = "./MapSpots/Regions/Asie/Israel.json"
const el109 = "./MapSpots/Regions/Asie/Japon.json"
const el110 = "./MapSpots/Regions/Asie/Jordanie.json"
const el111 = "./MapSpots/Regions/Asie/Kazakhstan.json"
const el112 = "./MapSpots/Regions/Asie/Kirghizistan.json"
// const el113 = "./MapSpots/Regions/Asie/Koweit.json"
const el114 = "./MapSpots/Regions/Asie/Laos.json"
// const el115 = "./MapSpots/Regions/Asie/Liban.json"
const el116 = "./MapSpots/Regions/Asie/Malaisie.json"
// const el117 = "./MapSpots/Regions/Asie/Maldives.json"
const el118 = "./MapSpots/Regions/Asie/Mongolie.json"
const el119 = "./MapSpots/Regions/Asie/Myanmar.json"
const el120 = "./MapSpots/Regions/Asie/Nepal.json"
const el121 = "./MapSpots/Regions/Asie/Oman.json"
const el122 = "./MapSpots/Regions/Asie/Ouzbekistan.json"
// const el123 = "./MapSpots/Regions/Asie/Pakistan.json"
// const el124 = "./MapSpots/Regions/Asie/Palestine.json"
const el125 = "./MapSpots/Regions/Asie/Philippines.json"
// const el126 = "./MapSpots/Regions/Asie/Qatar.json"
// const el127 = "./MapSpots/Regions/Asie/Singapour.json"
const el128 = "./MapSpots/Regions/Asie/SriLanka.json"
// const el129 = "./MapSpots/Regions/Asie/Syrie.json"
const el130 = "./MapSpots/Regions/Asie/Taiwan.json"
// const el131 = "./MapSpots/Regions/Asie/Tadjikistan.json"
const el132 = "./MapSpots/Regions/Asie/Thailande.json"
// const el133 = "./MapSpots/Regions/Asie/Timor.json"
// const el134 = "./MapSpots/Regions/Asie/Turkmenistan.json"
const el135 = "./MapSpots/Regions/Asie/Turquie.json"
const el136 = "./MapSpots/Regions/Asie/Vietnam.json"
// const el137 = "./MapSpots/Regions/Asie/Yemen.json"

//Europe
const el138 = "./MapSpots/Regions/Europe/Albanie.json"
const el139 = "./MapSpots/Regions/Europe/Allemagne.json"
// const el140 = "./MapSpots/Regions/Europe/Andorre.json"
const el141 = "./MapSpots/Regions/Europe/Autriche.json"
const el142 = "./MapSpots/Regions/Europe/Belgique.json"
// const el143 = "./MapSpots/Regions/Europe/Bielorussie.json"
const el144 = "./MapSpots/Regions/Europe/Bosnie.json"
// const el145 = "./MapSpots/Regions/Europe/Bulgarie.json"
const el146 = "./MapSpots/Regions/Europe/Chypre.json"
const el147 = "./MapSpots/Regions/Europe/Croatie.json"
const el148 = "./MapSpots/Regions/Europe/Danemark.json"
const el149 = "./MapSpots/Regions/Europe/Espagne.json"
const el150 = "./MapSpots/Regions/Europe/Estonie.json"
const el151 = "./MapSpots/Regions/Europe/Finlande.json"
// const el152 = "./MapSpots/Regions/Europe/France.json"
const el153 = "./MapSpots/Regions/Europe/Georgie.json"
const el154 = "./MapSpots/Regions/Europe/Grece.json"
const el155 = "./MapSpots/Regions/Europe/Hongrie.json"
const el156 = "./MapSpots/Regions/Europe/Irlande.json"
const el157 = "./MapSpots/Regions/Europe/Islande.json"
const el158 = "./MapSpots/Regions/Europe/Italie.json"
// const el159 = "./MapSpots/Regions/Europe/Kosovo.json"
// const el160 = "./MapSpots/Regions/Europe/Lettonie.json"
// const el161 = "./MapSpots/Regions/Europe/Liechtenstein.json"
// const el162 = "./MapSpots/Regions/Europe/Lituanie.json"
const el163 = "./MapSpots/Regions/Europe/Luxembourg.json"
const el164 = "./MapSpots/Regions/Europe/Macedoine.json"
const el165 = "./MapSpots/Regions/Europe/Malte.json"
// const el166 = "./MapSpots/Regions/Europe/IleMan.json"
// const el167 = "./MapSpots/Regions/Europe/Moldavie.json"
// const el168 = "./MapSpots/Regions/Europe/Monaco.json"
const el169 = "./MapSpots/Regions/Europe/Montenegro.json"
const el170 = "./MapSpots/Regions/Europe/Norvege.json"
const el171 = "./MapSpots/Regions/Europe/RegionsBas.json"
const el172 = "./MapSpots/Regions/Europe/Pologne.json"
const el173 = "./MapSpots/Regions/Europe/Portugal.json"
const el174 = "./MapSpots/Regions/Europe/Roumanie.json"
const el175 = "./MapSpots/Regions/Europe/RoyaumeUni.json"
const el176 = "./MapSpots/Regions/Europe/Russie.json"
const el177 = "./MapSpots/Regions/Europe/SaintMarin.json"
// const el178 = "./MapSpots/Regions/Europe/Serbie.json"
const el179 = "./MapSpots/Regions/Europe/Slovaquie.json"
const el180 = "./MapSpots/Regions/Europe/Slovenie.json"
const el181 = "./MapSpots/Regions/Europe/Suede.json"
const el182 = "./MapSpots/Regions/Europe/Suisse.json"
const el183 = "./MapSpots/Regions/Europe/Tchequie.json"
// const el184 = "./MapSpots/Regions/Europe/Ukraine.json"
// const el185 = "./MapSpots/Regions/Europe/Vatican.json"
const el1461 = "./MapSpots/Regions/Europe/ChypreNord.json"
const el1462 = "./MapSpots/Regions/Europe/Akrotiri.json"

// Oceanie
// const el186 = "./MapSpots/Regions/Oceanie/Australie.json"
// const el187 = "./MapSpots/Regions/Oceanie/Cook.json"
// const el188 = "./MapSpots/Regions/Oceanie/Fidji.json"
// const el189 = "./MapSpots/Regions/Oceanie/Kiribati.json"
// const el190 = "./MapSpots/Regions/Oceanie/Marshall.json"
const el191 = "./MapSpots/Regions/Oceanie/Micronesie.json"
// const el192 = "./MapSpots/Regions/Oceanie/Nauru.json"
// const el193 = "./MapSpots/Regions/Oceanie/Niue.json"
const el194 = "./MapSpots/Regions/Oceanie/NouvZelande.json"
// const el195 = "./MapSpots/Regions/Oceanie/Palaos.json"
// const el196 = "./MapSpots/Regions/Oceanie/Papoua.json"
// const el197 = "./MapSpots/Regions/Oceanie/Salomon.json"
// const el198 = "./MapSpots/Regions/Oceanie/Samoa.json"
// const el199 = "./MapSpots/Regions/Oceanie/Tonga.json"
// const el200 = "./MapSpots/Regions/Oceanie/Tuvalu.json"
const el201 = "./MapSpots/Regions/Oceanie/Vanuatu.json"


var elts = [
  el2, el5, el7, el8, el9, el13, el16, el19, el26, el27, el30, el32, el33, el34, el37, el41, el49,
  el56, el63, el64, el65, el69, el70, el72, el77, el78, el81,
  el92, el97, el99, el100, el102, el104, el105, el107, el109, el110, el111, el112, el114, el116
]

// var elts = [
//  , el118, el119, el120, el121, el122, el125, el128, el130, el132, el135, el136,
//  el138, el139, el141, el142, el144, el146, el147, el148, el149, el150, el151, el153, el154, el155, el156, el157, el158, el163, el164, el165, el169, el170, el171, el172, el173, el174, el175, el176, el177, el179, el180, el181, el182, el183, el1461, el1462,
//  el191, el194, el201
// ]

var eltsGeo = Array()

async function fetchRegions(file) {
    const res = await fetch(file);
    const Regions = await res.json();
    var style0 = {"color": Regions.features[0].properties.color, "weight": 1, "fillOpacity": 0.30}
    return L.geoJson(Regions, {"style": style0});
  }

for(var i = 0; i < elts.length; i++) {
    var j = await fetchRegions(elts[i]);
    eltsGeo.push(j);
}

export const RegionsGeo = eltsGeo;